### ISSUE TITLE
config/rootfs/rootfs.tar

### ISSUE THREAD

**Issue by szucsz** [GiyoMoon/mangopi-mq-quad-alpine#2]
I like your script, thank  you for your work.

I have a question: where is the config/rootfs/rootfs.tar file is coming from?

**Comment by GiyoMoon** [comment]
Hey! Glad you like it :) It's still very in-progress but I'm currently busy with other things.

I wanted to release a guide at some point where I explain all of it but didn't finish it.

I'm using the make-rootfs script from alpine to generate it. The important part is that it **needs** to run on an arm machine, or the rootfs won't be compatible with the mango pi.

Here's the rootfs section from the guide:

## Creating a root file system with Alpine
This needs to be run on an arm alpine machine to generate arm executables. Easiest way is probably to run it in a docker container (`docker run --platform linux/arm64/v8 alpine`)
```shell
git clone --depth 1 https://github.com/alpinelinux/alpine-make-rootfs.git
cd alpine-make-rootfs/
./alpine-make-rootfs --branch v3.17 --packages 'openrc apk-tools wireless-regdb chrony iwd openssh cloud-utils-growpart e2fsprogs-extra' rootfs.tar
cd ..
```

**Comment by szucsz** [comment]
awesome, thank you for your quick response :)

**Comment by GiyoMoon** [comment]
You're welcome! Feel free to reach out again if you have any other questions :)
