### ISSUE TITLE
Which version of kernel was used?

### ISSUE THREAD

**Issue by wwng2333** [GiyoMoon/mangopi-mq-quad-alpine#5]
Hi there, i found a problem that the script will always pull the latest stable kernel for compile, which makes me met a lot of problems.
So can you provide a kernel version number which is tested so that i can edit the script.
https://github.com/GiyoMoon/mangopi-mq-quad-alpine/blob/644d3001567873dc43eb45556be6319111f00382/build_image.sh#L37

**Comment by wwng2333** [comment]
I test linux-6.1.118, rtw88 compile normal.

**Comment by szucsz** [comment]
@wwng2333 does it build for you? I used to be able to build but with the latest clones of the external repos I  do not get a working image unfortunately

**Comment by wwng2333** [comment]
> @wwng2333 does it build for you? I used to be able to build but with the latest clones of the external repos I do not get a working image unfortunately

I already built that with kernel 6.1.118, but not able to boot. Now i'm using [dietpi](https://github.com/wareck/DietPi-MangoPI-MQ-Quad/releases).

**Comment by GiyoMoon** [comment]
Hey! I actually don't remember what kernel version I used. Looking at the commit dates and kernel history, I'm assuming it was between `6.0` and `6.2`. This repo was for the time where I was tinkering with the mango pi but eventually I stopped using it. I hope you can get some useful stuff out of it :) There is also a `wip` branch that has an early version of a guided installation documentation: https://github.com/GiyoMoon/mangopi-mq-quad-alpine/blob/wip/guided.md
